# Configuration sponsoring GitHub.
# Remplace par tes propres handles quand tu en as.

github: [Micka420-collab]
# patreon: ""
# open_collective: ""
# ko_fi: ""
# tidelift: ""
# community_bridge: ""
# liberapay: ""
# issuehunt: ""
# otechie: ""
# lfx_crowdfunding: ""
# polar: ""
# buy_me_a_coffee: ""
# thanks_dev: ""
# custom: ["https://"]
