apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis.yaml
  - postgres.yaml
  - qdrant.yaml
  - mosquitto.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: jarvis
